# Generated by Django 5.2.9 on 2026-02-09 14:50

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام نویسنده')),
                ('description', models.TextField(verbose_name='درباره نویسنده')),
                ('photo', models.ImageField(blank=True, default='author_photos/default.jpg', upload_to='author_photos')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='نام دسته')),
                ('description', models.TextField(verbose_name='توضیحات دسته')),
                ('thumbnail', models.ImageField(blank=True, default='cat_thumbnails/default.jpg', upload_to='cat_thumbnails', verbose_name='عکس دسته')),
                ('slug', models.SlugField(max_length=300)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='نام کتاب')),
                ('description', ckeditor.fields.RichTextField(verbose_name='جزئیات')),
                ('summary', models.TextField(verbose_name='خلاصه')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('discount', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف')),
                ('publisher', models.CharField(max_length=250, verbose_name='ناشر')),
                ('translator', models.CharField(blank=True, max_length=250, null=True, verbose_name='مترجم')),
                ('thumbnail', models.ImageField(default='thumbnails/default.jpg', upload_to='thumbnails', verbose_name='عکس اصلی')),
                ('pdf_file', models.FileField(upload_to='pdf', verbose_name='فایل pdf')),
                ('rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('slug', models.SlugField(blank=True, max_length=600, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اضافه شدن محصول')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='core.author', verbose_name='نویسنده')),
                ('category', models.ManyToManyField(related_name='books', to='core.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب',
            },
        ),
    ]
