# Generated by Django 5.2.9 on 2025-12-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='hmmmm', verbose_name='جزئیات'),
            preserve_default=False,
        ),
    ]
