# Generated by Django 5.2.9 on 2025-12-07 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام نویسنده')),
                ('description', models.TextField(verbose_name='درباره نویسنده')),
                ('photo', models.ImageField(blank=True, default='author_photos/default.jpg', upload_to='author_photos')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='core.author', verbose_name='نویسنده'),
        ),
    ]
