# Generated by Django 5.2.9 on 2025-12-08 21:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_remove_book_category_book_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوای نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ کامنت')),
                ('score', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('status', models.CharField(blank=True, choices=[('a', 'پذیرفته شده'), ('r', 'رد شده'), ('p', 'در حال بررسی')], default='p', max_length=3, verbose_name='وضعیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده نظر')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.book', verbose_name='کتاب')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.comment', verbose_name='پاسخ به')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظر',
            },
        ),
    ]
